print('What is your name?')
name = input()
print('Hello, ' + name + '!')
print('How old are you?')
age = int(input())
birth_year = 2018 - age
print('You was born in ' + str(birth_year) + 'year')
print('You are very old, are you happy?')
answer = input()
print ('Bye')
input('print Enter to exit')